### ISSUE TITLE
Support for logstash 2

### ISSUE THREAD

**Issue by MirkoTV** [alcanzar/logstash-filter-memorize#2]
I was wondering if this plugin will be supported by logstash 2.0.0

**Comment by sergioedo** [comment]
I've tested it with Logstash 2.1, and it works modifying gem dependencies with '< **3**.0.0' in logstash-filter-memorize.gemspec:

`s.add_runtime_dependency "logstash-core", '>= 1.4.0', '< 3.0.0'`

**Comment by alcanzar** [comment]
based on @sergioedo comment, I'll update the gemspec and push a new version.  Thanks!  I haven't had time to look at this.

**Comment by sergioedo** [comment]
Thanks @alcanzar!
